<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="gk" failures="2" tests="4" name="Test" time="46.818" errors="0" timestamp="2025-02-16T17:29:53 IST">
  <testcase classname="testCases.LoginTestDDT" name="verify_loginDDT" time="10.725">
    <failure type="java.lang.AssertionError" message="Login should have succeeded but did not. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login should have succeeded but did not. expected [true] but found [false]
at testCases.LoginTestDDT.verify_loginDDT(LoginTestDDT.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.LoginTestDDT" name="verify_loginDDT" time="10.567"/>
  <testcase classname="testCases.LoginTestDDT" name="verify_loginDDT" time="10.602"/>
  <testcase classname="testCases.LoginTestDDT" name="verify_loginDDT" time="10.623">
    <failure type="java.lang.AssertionError" message="Login should have succeeded but did not. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login should have succeeded but did not. expected [true] but found [false]
at testCases.LoginTestDDT.verify_loginDDT(LoginTestDDT.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
