<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-14T23:04:11 IST" name="Suite" finished-at="2025-02-14T23:04:16 IST" duration-ms="5303">
    <groups>
      <group name="regression">
        <method signature="EndToEndTestCase.verifyE2EFuncionality()[pri:0, instance:testCases.EndToEndTestCase@6caf0677]" name="verifyE2EFuncionality" class="testCases.EndToEndTestCase"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2025-02-14T23:04:11 IST" name="Test" finished-at="2025-02-14T23:04:16 IST" duration-ms="5303">
      <class name="testCases.EndToEndTestCase">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testCases.EndToEndTestCase@6caf0677]" started-at="2025-02-14T23:04:11 IST" name="setup" finished-at="2025-02-14T23:04:14 IST" duration-ms="2235" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyE2EFuncionality()[pri:0, instance:testCases.EndToEndTestCase@6caf0677]" started-at="2025-02-14T23:04:14 IST" name="verifyE2EFuncionality" finished-at="2025-02-14T23:04:16 IST" duration-ms="2554" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
No New Todo Created expected [New Todo created successfully!3] but found [New Todo created successfully!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
No New Todo Created expected [New Todo created successfully!3] but found [New Todo created successfully!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.EndToEndTestCase.verifyE2EFuncionality(EndToEndTestCase.java:132)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyE2EFuncionality -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.EndToEndTestCase@6caf0677]" started-at="2025-02-14T23:04:16 IST" name="tearDown" finished-at="2025-02-14T23:04:16 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.EndToEndTestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
